/*
 * Tims DNS API
 * Tims DNS Api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sentry42@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.tim.dns.model;

import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents the status of a customer account
 */
@ApiModel(description = "Represents the status of a customer account")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-12-16T15:33:42.028Z")
public class DnsRecord {
   @JsonProperty("hostname")
   private String hostname = null;

   @JsonProperty("ip")
   private String ip = null;

   public DnsRecord hostname(String hostname) {
      this.hostname = hostname;
      return this;
   }

   /**
    * A reference number identifying the bill payments processor, bill issuer, and customer
    * 
    * @return hostname
    **/
   @JsonProperty("hostname")
   @ApiModelProperty(required = true, value = "A reference number identifying the bill payments processor, bill issuer, and customer")
   @NotNull
   public String getHostname() {
      return hostname;
   }

   public void setHostname(String hostname) {
      this.hostname = hostname;
   }

   public DnsRecord ip(String ip) {
      this.ip = ip;
      return this;
   }

   /**
    * The effective date of the current billing period
    * 
    * @return ip
    **/
   @JsonProperty("ip")
   @ApiModelProperty(value = "The effective date of the current billing period")
   public String getIp() {
      return ip;
   }

   public void setIp(String ip) {
      this.ip = ip;
   }

   @Override
   public boolean equals(java.lang.Object o) {
      if (this == o) {
         return true;
      }
      if (o == null || getClass() != o.getClass()) {
         return false;
      }
      DnsRecord dnsRecord = (DnsRecord) o;
      return Objects.equals(this.hostname, dnsRecord.hostname) && Objects.equals(this.ip, dnsRecord.ip);
   }

   @Override
   public int hashCode() {
      return Objects.hash(hostname, ip);
   }

   @Override
   public String toString() {
      StringBuilder sb = new StringBuilder();
      sb.append("class DnsRecord {\n");

      sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
      sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
      sb.append("}");
      return sb.toString();
   }

   /**
    * Convert the given object to string with each line indented by 4 spaces (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
      if (o == null) {
         return "null";
      }
      return o.toString().replace("\n", "\n    ");
   }
}
